### ISSUE TITLE
[$60] Notifications from CoderBot are not created correctly

### ISSUE THREAD

**Issue by maxceem** [topcoder-platform/tc-notifications#9]
One of the notifications is being created in a wrong way when new event `joan-26673.notifications.connect.project.post.created` arrives. And the next INSERT query is performed:
```sql
INSERT INTO "Notifications" ("id","userId","type","contents","read","createdAt","updatedAt") VALUES (DEFAULT,'CoderBot','notifications.connect.project.post.created.v2','{"topicId":"1926","postId":6854,"postContent":"<p>test</p>\n\n<p>​</p>","userId":40152856,"projectId":"2372","toTopicStarter":true,"projectName":"test","userHandle":"pshah_manager","userFullName":"Parth Manager"}',false,'2018-01-06 09:26:35.973 +00:00','2018-01-06 09:26:35.973 +00:00') RETURNING *
```
It contains `'CoderBot'` value for the column `userId`. But is has to contain a numeric `userId` instead. Because of this the query fails.

The whole log when event `joan-26673.notifications.connect.project.post.created` arrives is below.
```
info: Handle Kafka event message; Topic: joan-26673.notifications.connect.project.post.created; Partition: 0; Offset: 153; Message: {"topicId":"1926","postId":6854,"postContent":"<p>test</p>\n\n<p>​</p>","userId":40152856,"projectId":"2372"}.
debug: ENTER listNotifications
debug: input arguments
debug: { query: { read: 'false', limit: '1000' }, userId: 40152922 }
Executing (default): SELECT "id", "userId", "topic", "deliveryMethod", "value" FROM "NotificationSettings" AS "NotificationSetting" WHERE "NotificationSetting"."userId" = 40152922;
Executing (default): SELECT count(*) AS "count" FROM "Notifications" AS "Notification" WHERE "Notification"."userId" = 40152922 AND "Notification"."read" = false;
Executing (default): SELECT "id", "userId", "type", "contents", "read", "createdAt", "updatedAt" FROM "Notifications" AS "Notification" WHERE "Notification"."userId" = 40152922 AND "Notification"."read" = false ORDER BY "Notification"."createdAt" DESC LIMIT 1000 OFFSET 0;
debug: EXIT listNotifications
debug: output arguments
debug: output arguments
debug: { items: [], offset: 0, limit: 1000, totalCount: 0 }
debug: ENTER listNotifications
debug: input arguments
debug: { query: { read: 'false', limit: '1000' }, userId: 40153455 }
Executing (default): SELECT "id", "userId", "topic", "deliveryMethod", "value" FROM "NotificationSettings" AS "NotificationSetting" WHERE "NotificationSetting"."userId" = 40153455;
Executing (default): SELECT count(*) AS "count" FROM "Notifications" AS "Notification" WHERE "Notification"."userId" = 40153455 AND "Notification"."read" = false;
Executing (default): SELECT "id", "userId", "type", "contents", "read", "createdAt", "updatedAt" FROM "Notifications" AS "Notification" WHERE "Notification"."userId" = 40153455 AND "Notification"."read" = false ORDER BY "Notification"."createdAt" DESC LIMIT 1000 OFFSET 0;
debug: EXIT listNotifications
debug: output arguments
debug: output arguments
debug: { items: [], offset: 0, limit: 1000, totalCount: 0 }
Executing (default): INSERT INTO "Notifications" ("id","userId","type","contents","read","createdAt","updatedAt") VALUES (DEFAULT,'CoderBot','notifications.connect.project.post.created.v2','{"topicId":"1926","postId":6854,"postContent":"<p>test</p>\n\n<p>​</p>","userId":40152856,"projectId":"2372","toTopicStarter":true,"projectName":"test","userHandle":"pshah_manager","userFullName":"Parth Manager"}',false,'2018-01-06 09:26:35.973 +00:00','2018-01-06 09:26:35.973 +00:00') RETURNING *;
Executing (default): INSERT INTO "Notifications" ("id","userId","type","contents","read","createdAt","updatedAt") VALUES (DEFAULT,'40152856','notifications.connect.project.post.created.v2','{"topicId":"1926","postId":6854,"postContent":"<p>test</p>\n\n<p>​</p>","userId":40152856,"projectId":"2372","projectRole":"owner","projectName":"test","userHandle":"pshah_manager","userFullName":"Parth Manager"}',false,'2018-01-06 09:26:35.974 +00:00','2018-01-06 09:26:35.974 +00:00') RETURNING *;
error:  SequelizeDatabaseError: invalid input syntax for integer: "CoderBot"
    at Query.formatError (/Users/maks/dev/topcoder/72_tc_connect_bug_bash_06/tc-notifications/node_modules/sequelize/lib/dialects/postgres/query.js:356:16)
    at query.catch.err (/Users/maks/dev/topcoder/72_tc_connect_bug_bash_06/tc-notifications/node_modules/sequelize/lib/dialects/postgres/query.js:86:18)
    at tryCatcher (/Users/maks/dev/topcoder/72_tc_connect_bug_bash_06/tc-notifications/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/maks/dev/topcoder/72_tc_connect_bug_bash_06/tc-notifications/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/Users/maks/dev/topcoder/72_tc_connect_bug_bash_06/tc-notifications/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/Users/maks/dev/topcoder/72_tc_connect_bug_bash_06/tc-notifications/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/maks/dev/topcoder/72_tc_connect_bug_bash_06/tc-notifications/node_modules/bluebird/js/release/promise.js:689:18)
    at Async._drainQueue (/Users/maks/dev/topcoder/72_tc_connect_bug_bash_06/tc-notifications/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/Users/maks/dev/topcoder/72_tc_connect_bug_bash_06/tc-notifications/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/Users/maks/dev/topcoder/72_tc_connect_bug_bash_06/tc-notifications/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
```

**Comment by maxceem** [comment]
@gondzo I don't know if anybody got notified about new issues here. So I tag you just in case.

**Comment by gondzo** [comment]
thank you for reporting. 
can we just set -1 for userId and keep Coder Bot for handle and full name?

**Comment by gondzo** [comment]
or the issue here is that tcwebservice is renamed to Coder Bot and added to userId instead of handle?

**Comment by maxceem** [comment]
I'm not sure how it happens.

- I run `tc-notifications` locally
- Open https://connect.topcoder-dev.com/projects/2378 and reply to some post
- In the `tc-notifications` console I see how the next message comes: 
```
Topic: joan-26673.notifications.connect.project.post.created; Partition: 0; Offset: 158; Message: {"topicId":"1928","postId":6880,"postContent":"<p>asdasd</p>","userId":40152856,"projectId":"2378"}.
```
- `tc-notifcation` creates two notifications and try to insert them to DB
- A good one 
```sql
INSERT INTO "Notifications" ("id","userId","type","contents","read","createdAt","updatedAt") VALUES (DEFAULT,'40152856','notifications.connect.project.post.created','{"topicId":"1928","postId":6880,"postContent":"<p>asdasd</p>","userId":40152856,"projectId":"2378","projectRole":"owner","projectName":"test development project","userHandle":"pshah_manager"}',false,'2018-01-06 12:59:13.097 +00:00','2018-01-06 12:59:13.097 +00:00') RETURNING *;
```
- And a bad one where instead of `userId` which has to be number there is 'CoderBot'
```sql
INSERT INTO "Notifications" ("id","userId","type","contents","read","createdAt","updatedAt") VALUES (DEFAULT,'CoderBot','notifications.connect.project.post.created','{"topicId":"1928","postId":6880,"postContent":"<p>asdasd</p>","userId":40152856,"projectId":"2378","toTopicStarter":true,"projectName":"test development project","userHandle":"pshah_manager"}',false,'2018-01-06 12:59:13.096 +00:00','2018-01-06 12:59:13.096 +00:00') RETURNING *;
```

From the quick check I cannot see how a text value 'CoderBot' (probably user handle) can appear at the `userId` place.

I'm still checking...

**Comment by maxceem** [comment]
Got it.
When we request topic details it returns 'CoderBot` as a `userId`
```json
{ id: 1928,
  dbId: 3129,
  reference: 'project',
  referenceId: '2378',
  date: '2018-01-06T12:23:34.264Z',
  lastActivityAt: '2018-01-06T13:09:02.640Z',
  title: 'Your project has been created, and we\'re ready for your specification',
  read: true,
  userId: 'CoderBot',
}
```

**Comment by maxceem** [comment]
Just in case. I can fix it. 
But this behavior is different from what was before so I'm not what was the reason for changes and where it should be fixed:
- userId in topic DB records
- filter out such messages at all in `tc-notifications`
- process such messages in `tc-notifications` in some way

**Comment by gondzo** [comment]
I think the cause is in recent changes to tc-message service
for now we can just use some invalid userId in tc-notifications when we get a non integer user id

**Comment by maxceem** [comment]
This userId defines the user which will get the notification. If we always define invalid userId and put into the DB, then we will save notification which nobody will ever get. Probably we can skip such notifications and don't add them to the DB at all. What do you think?

**Comment by gondzo** [comment]
ah, so the notification was meant for CoderBot user ? if so, we can just
skip those notifications

**Comment by maxceem** [comment]
Can we filter only 'CoderBot' userIds? So if non-integer value comes in some other situation we can see an error.

**Comment by gondzo** [comment]
yes, that is even better

**Comment by maxceem** [comment]
This is done by [PR#15](https://github.com/topcoder-platform/tc-notifications/pull/15)

Cannot assign `Ready for Review` label here.
